server:
  port: 8000

spring:
  datasource:
   # url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2b8
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource

  application:
    name: SCW-PROJECT

  redis:
    password: 123456
    host: 192.168.188.129
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    path: F:\JAVA4\log
  level:
    com:
      offcn: debug
oss:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  bucketDomain: 20201209-xyk.oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4G22TuASRy4LBXtvxKNj
  accessKeySecret: 5bbYuwKMOAVS7ZVMh6LtxCPoXNO3a5
  bucketName: 20201209-xyk

#mybatis:
#  mapper-locations: classpath:com/offcn/project/mapper
#  config-location: classpath:mybatis/mybatis-config.xml