server:
  port: 7000

spring:
  datasource:
   # url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2b8
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource

  application:
    name: SCW-USER

  redis:
    password: 123456
    host: 192.168.188.129
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    path: F:\JAVA4\log
  level:
    com:
      offcn: debug
sms:
  host: http://dingxin.market.alicloudapi.com
  path: /dx/sendSms
  method: POST
  appCode: APPCODE 61e0d0b6a4bf44e4b3d0375335f12c98

#mybatis:
#  mapper-locations: classpath:com/offcn/user/mapper
#  config-location: classpath:mybatis/mybatis-config.xml